version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - .:/app
      - /app/build
      - /app/.gradle
    restart: always
    command: java -jar ./build/libs/festino-admin-0.0.1-SNAPSHOT.jar